export const mockData = [
  { question_id: 1, q_type: "S", answer: 3 },
  { question_id: 2, q_type: "I", answer: 5 },
  { question_id: 3, q_type: "D", answer: 1 },
  { question_id: 4, q_type: "C", answer: 3 },
  { question_id: 5, q_type: "D", answer: 1 },
  { question_id: 6, q_type: "I", answer: 2 },
  { question_id: 7, q_type: "S", answer: 3 },
  { question_id: 8, q_type: "C", answer: 4 },
  { question_id: 9, q_type: "I", answer: 5 },
  { question_id: 10, q_type: "S", answer: 3 },
  { question_id: 11, q_type: "C", answer: 5 },
  { question_id: 12, q_type: "D", answer: 1 },
  { question_id: 13, q_type: "D", answer: 1 },
  { question_id: 14, q_type: "I", answer: 5 },
  { question_id: 15, q_type: "C", answer: 5 },
  { question_id: 16, q_type: "S", answer: 3 },
];
